### ISSUE TITLE
Do blocks should inherit `async` modifier

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#10]
Do blocks should inherit `async` modifier from their function context, because `do` blocks are not functions themselves.
```js
let foo = async fn (a, b) {
  let bar = do {
    await fetchSomething()
  }
}
```

**Comment by jamiebuilds** [comment]
They are two different things, a `do async` can be used within a function to create concurrent code.

```js
let fn = async fn () {
  let value = do {
    await sleep(100)
    42
  }
  assert(value is 42)
}
```

```js
let fn = async fn () {
  let value = do async {
    await sleep(100)
    42
  }
  assert(value is Async<42>)
}
```

**Comment by jamiebuilds** [comment]
You're determining with block the `await` belongs to

**Comment by aleclarson** [comment]
Oh okay. Very cool. Maybe a comparison of both should be in the readme?

**Comment by aleclarson** [comment]
Need more docs about `Async` too! :)
