### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by SCKelemen** [jamiebuilds/ghost-lang#11]
You've mentioned you're interested in targeting wasm. Are you looking to write a compiler, and if so are you looking for help?

**Comment by jamiebuilds** [comment]
I have 1-2 months off before I start my next job, I think I'm going to try getting a compiler working in that time (although no way it supports everything I have spec'd out so far).

I mostly want to do this as a challenge to myself. If it ends up going somewhere I'm happy to turn it into a real project and invite others to come work on it.

**Comment by SCKelemen** [comment]
Do you know in which language you'll write the first implementation?

**Comment by jamiebuilds** [comment]
lol, probably JavaScript to get something working because I'm already so productive in it.

There's a lot of details to be worked out in Ghost so if it ends up being a real thing then I'll probably toss out my initial implementation in favor of Rust or something.

**Comment by mpourismaiel** [comment]
I'm really interested to have this as a Webpack loader. Maybe with the compiler we would have the opportunity to have that. This would make coding for frontend a bit less of a hassle. WASM could be of use but still legacy support is something to think about. Hope something great comes of this. Good luck. And if you need any help, count me in.

**Comment by SCKelemen** [comment]
Yeah, I'd be interested in helping but most of the compilers and runtimes I have worked on have been written in C++, C#, Go, and Pony. Would you only be targeting WASM, or would you want to support other architectures, too?

**Comment by jamiebuilds** [comment]
I expect Wasm to propogate to a lot of different systems over the next few years. I think it's the only one worth targeting with a new language like this

**Comment by motss** [comment]
It's going to be an interesting project. Let me know if any help is needed.

**Comment by darol100** [comment]
Same as @motss . 

I will be highly interested in helping out on this project.

**Comment by kayandra** [comment]
I don't know much about compiler development, but I'm willing to learn Rust and how to build compilers just to work on this.

**Comment by nevzatseferoglu** [comment]
I am also interested in building  compiler.Please share tutorial that you find to improve in this field

**Comment by MH15** [comment]
Interested in helping.
