### ISSUE TITLE
Uncaught effects

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#12]
What happens to uncaught effects?

**Comment by jamiebuilds** [comment]
```
UncaughtEffectError: Effect was never caught by a handler: 'myEffect'
   ...stack trace...
```

**Comment by aleclarson** [comment]
Crazy idea: Prepend the `@` symbol to any function call to assume purity. Maybe perform some memoization? Any uncaught effects would crash at the callsite.
