### ISSUE TITLE
Tuple types

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#13]
I assume it's just:
```ts
type Foo = [Number, String]

let foo: Foo = [1, 'hi']
```

**Comment by jamiebuilds** [comment]
I don't have tuples in the language because lightweight records are better, I don't think it needs a type syntax.

**Comment by aleclarson** [comment]
Is there no concept of an argument list? Would that be a record, too?

**Comment by jamiebuilds** [comment]
In the case of:

```js
fn (...rest) {}
```

`rest` is a fixed length array with the type `Array<T>` where `T` is the union of all the types of values in `rest`

**Comment by aleclarson** [comment]
Clobbering the order would remove type-safety from rest-then-spread-call.
```ts
type Foo = fn (a: number, b: string): number
type Bar = fn (a: string, b: number): number

// Are the type declarations are required here?
let bar: Bar = fn (...args) { 1 }
let foo: Foo = fn (...args) {
  bar(...args) // no compiler error, yet [number, string] and [string, number] are incompatible
}
```

**Comment by jamiebuilds** [comment]
Well there _would_ be compiler errors because `Number | String` cannot flow into `Number` or `String`

**Comment by aleclarson** [comment]
So rest-then-spread is not possible? If so, what's the workaround?
