### ISSUE TITLE
Language Semantics

### ISSUE THREAD

**Issue by josegomezr** [jamiebuilds/ghost-lang#24]
Hey there, awesome spec, It's really simple, but I've some questions about semantics (or should it be called *hues*?).

### What's the difference between List and Array
Aside from syntax, what makes a list a list, and an array an array. An array doesn't have comprehension as list does? Does lists have negative indexes?

### What's the difference between Record and Map
Aside from syntax, what makes a record a record, and a map a map. Does maps behave like python's dict? Does records behave like pythons namedtuples?

**Comment by aleclarson** [comment]
See [this comment](https://github.com/jamiebuilds/ghost-lang/issues/2#issuecomment-435115318).

I assume that Records/Maps will be included.
