### ISSUE TITLE
What are records?

### ISSUE THREAD

**Issue by darol100** [jamiebuilds/ghost-lang#29]
It's unclear to me when and how to use records?

[Records](https://github.com/jamiebuilds/ghost-lang?fbclid=IwAR3zsnFbsleROrwL5sGuTBoWdPd_Z4FxLNdQ7x2KdbAp1S8C0lU9gHUIZMY#records)
```
let three = :three

let record = {
  one: 1,
  two: 2,
  [three]: 3,
}

let one = record.one
let two = record[:two]
let three = record[three]

let newRecord = {
  one: 'default',
  ...record,
  three: 'new value',
}
````

How do records work?

**Comment by jamiebuilds** [comment]
Think of them as super lightweight objects, where all the keys are symbols instead of strings or something
