### ISSUE TITLE
Readonly sugar

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#4]
WDYT of adding sugar for readonly properties (or even objects/arrays)?

I like Flow's `+` syntax.

**Comment by jamiebuilds** [comment]
Everything in the language will be immutable unless marked otherwise, there is currently no way to mutate values in Ghost

**Comment by aleclarson** [comment]
@jamiebuilds Can I assume generators will be immutable, too? (so no need for libraries like https://github.com/pelotom/immutagen)

**Comment by jamiebuilds** [comment]
Ghost doesn't have "generators" as they are in Python and JavaScript. Ghost has "iterable functions" and `yield` does not wait for a value to be passed to `iter.next(value)`.

As such `iter.next()` is idempotent (and immutable).
