### ISSUE TITLE
🚲Why `effect` instead of `yield`?

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#5]
And should the function be marked as effectful (eg: `*fn () {}`)?

Any function that throws would need the asterisk, IMO.

**edit:** And maybe use `co` instead of `*fn`?

**Comment by aleclarson** [comment]
Just saw that `yield` is used for iterables. Maybe `for-as` can "just work" with any coroutine, not just iterables?

**Comment by aleclarson** [comment]
Also, maybe make it so generators (eg: `*fn`/`co` functions) are async by default. Since whether or not a generator is async is really an implementation detail, right?

**Comment by jamiebuilds** [comment]
`effect`'s behavior is somewhere in between `throw` and `yield`, all three are valid programming patterns

**Comment by aleclarson** [comment]
Can a function all four (`effect`, `throw`, `yield`, `await`) or are there restrictions?

**Comment by jamiebuilds** [comment]
Assuming it's a `fn () async iter {...}`, then yes it can use all four

**Comment by aleclarson** [comment]
What can I do with `effect` that I can't do with `throw`?

**Comment by jamiebuilds** [comment]
You can `resume` it from a `catch {}` handler with a value
