### ISSUE TITLE
import .. as

### ISSUE THREAD

**Issue by aleclarson** [jamiebuilds/ghost-lang#6]
```js
// Import all under a namespace
import './utils/currency' as currency

// Import some into this namespace
import './utils/currency' as { a, b }

// Import all into this namespace
import './utils/currency'
```

*Side note:* I hope the lack of string quotes is optional.

Yay or nay?

**Comment by aleclarson** [comment]
Could also do:
```js
let currency = import './utils/currency'
let { a, b } = import './utils/currency'
```

**Comment by jamiebuilds** [comment]
The import location specifier should come first for IDEs. The lack of quotes is intentional as these specifiers are not analygous to file paths. I was already thinking of a `import ./foo as bar` syntax though.

**Comment by jamiebuilds** [comment]
updated
